[connections.neon]
url="postgresql://crimes_owner:npg_QUkH7TfKZlF8@ep-curly-recipe-a50hnh5z-pooler.us-east-2.aws.neon.tech/crimes?sslmode=require"

[mongodb]
uri = "mongodb+srv://IngEnigma:0ZArHx18XQIFWPHu@bigdata.iwghsuv.mongodb.net/?retryWrites=true&w=majority&appName=BigData"
